[build]
  base = ""
  command = "cd apps/widget && pnpm install && pnpm run build"
  publish = "apps/widget/dist"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "8"

[functions]
  directory = "packages/api/netlify-functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/api/*"
  [headers.values]
    Netlify-CDN-Cache-Control = "public, s-maxage=30"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200