[build]
  command = "cd xboard && pnpm install && cd apps/widget && pnpm run build"
  publish = "xboard/apps/widget/dist"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "8"

[functions]
  directory = "xboard/netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/api/*"
  [headers.values]
    Netlify-CDN-Cache-Control = "public, s-maxage=30"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200